// import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./Redux/StoreProvidor";

export const metadata = {
  title: "BYLD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      {/* <meta name="viewport" content="width=device-width, initial-scale=50%" /> */}
      <link rel="icon" href="/favicon.ico" />
      </head>
      <body >
        <StoreProvider >
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
