import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./Redux/StoreProvidor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BYLD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider >
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
